### ISSUE TITLE
OS X java support

### ISSUE THREAD

**Issue by vellt360** [LWJGL/lwjgl#107]
I am having troubles properly loading this. 
If someone could help that would be great. Here's the end of the log
If there's any other part you need I can give you that.
[17:29:34] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[?:1.6.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[?:1.6.0_65]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Users/17zgordon_84/Documents/untitled folder/untitled folder/FTB/EthosLPPack/natives/liblwjgl.jnilib
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1712) ~[?:1.6.0_65]
	at java.lang.Runtime.load0(Runtime.java:770) ~[?:1.6.0_65]
	at java.lang.System.load(System.java:1019) ~[?:1.6.0_65]
	at org.lwjgl.Sys$1.run(Sys.java:70) ~[lwjgl-2.9.2-nightly-20140822.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.2-nightly-20140822.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:95) ~[lwjgl-2.9.2-nightly-20140822.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:112) ~[lwjgl-2.9.2-nightly-20140822.jar:?]
	at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2659) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more

**Comment by vellt360** [comment]
This is due to the Mac software, you can't even load this version of minecraft in vanilla
