### ISSUE TITLE
[Windows] OpenGL 2.0 or higher with the FBO extension is required

### ISSUE THREAD

**Issue by raderio** [LWJGL/lwjgl#135]
Windows 10(64-bit), Intel graphics card

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 1.1.0
Type: OpenGL
Version: 1:1:0
Vendor: Microsoft Corporation
Renderer: GDI Generic
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGLInstances(LwjglGraphics.java:346)
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGL(LwjglGraphics.java:225)
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:216)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:142)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

OpenGL Viewer shows that it is 4.0

**Comment by Ruedii** [comment]
Are you still having issues?

It seems the library is running the wrong OpenGL driver.  It is using the old software rendering routine from Microsoft instead of the hardware driver.  

Try updating your video driver.  Substantially updated drivers for your chipset are available from Intel's website.
