### ISSUE TITLE
RuntimeException thrown on log call

### ISSUE THREAD

**Issue by skoskav** [LWJGL/lwjgl#139]
Using 3.0.0 build 90

```
Exception in thread "main" java.util.MissingFormatArgumentException: Format specifier '%X'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:326)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:296)
	at org.skoskav.test1.Test.init(Test.java:97)
	at org.skoskav.test1.Test.main(Test.java:45)
```

It seems that this line org.lwjgl.opengl.GL@326
`apiLog(String.format("An OpenGL context was in an error state before the creation of its capabilities instance. Error: 0x%X" + errorCode));`

...should be:
`apiLog(String.format("An OpenGL context was in an error state before the creation of its capabilities instance. Error: 0x%X", errorCode));`

Though note the inconsistency with org.lwjgl.opengles.GLES@204 which wraps its error code in brackets:

`apiLog(String.format("An OpenGL ES context was in an error state before the creation of its capabilities instance. Error: [0x%X]", errorCode));`

**Comment by httpdigest** [comment]
I think this issue was fixed with the pull request https://github.com/LWJGL/lwjgl3/pull/194
You can use version 3.0.1 build 6 (Maven 3.0.1-SNAPSHOT) which contains the fix.
