### ISSUE TITLE
Error: Can't load AMD 64-bit .dll on a IA 32-bit platform

### ISSUE THREAD

**Issue by RMuskovets** [LWJGL/lwjgl#149]
When I tried to run the application, I had this error: 
**Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Roman\AppData\Local\Temp\libgdxRoman\929689568\lwjgl.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform**
	_at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at org.lwjgl.openal.AL.<clinit>(AL.java:59)_
	at com.badlogic.gdx.backends.openal.OpenALAudio.<init>(OpenALAudio.java:70)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:80)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:64)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:60)
	at com.test.desktop.DesktopLauncher.main(DesktopLauncher.java:11)

My system: Windows 7 SP1 32-bit, Intel 3.3 GHz

**Comment by daviel** [comment]
Did you find a solution for this? I encountered the same problem...

**Comment by RMuskovets** [comment]
i changed system to 64-bit

**Comment by sskant786** [comment]
my system is already of 64-bit still getting the issue.
